export type ComponentCategory =
  "Forms" | "Layout" | "Navigation" | "Overlay" | "Feedback" | "Content"

export type ComponentDefinition = {
  name: string
  label: string
  category: ComponentCategory
  description: string
}

export const componentCatalog: ComponentDefinition[] = [
  {
    name: "accordion",
    label: "Accordion",
    category: "Content",
    description: "Expandable content sections.",
  },
  {
    name: "alert",
    label: "Alert",
    category: "Feedback",
    description: "Persistent status messages.",
  },
  {
    name: "alert-dialog",
    label: "Alert Dialog",
    category: "Overlay",
    description: "Confirmation for important actions.",
  },
  {
    name: "aspect-ratio",
    label: "Aspect Ratio",
    category: "Layout",
    description: "Fixed-ratio containers.",
  },
  {
    name: "attachment",
    label: "Attachment",
    category: "Content",
    description: "Files with metadata and actions.",
  },
  {
    name: "avatar",
    label: "Avatar",
    category: "Content",
    description: "People and team identities.",
  },
  {
    name: "badge",
    label: "Badge",
    category: "Feedback",
    description: "Compact status labels.",
  },
  {
    name: "breadcrumb",
    label: "Breadcrumb",
    category: "Navigation",
    description: "A path through your app.",
  },
  {
    name: "bubble",
    label: "Bubble",
    category: "Content",
    description: "Conversation bubbles.",
  },
  {
    name: "button",
    label: "Button",
    category: "Forms",
    description: "Actions, variants and states.",
  },
  {
    name: "button-group",
    label: "Button Group",
    category: "Forms",
    description: "Related actions, grouped together.",
  },
  {
    name: "calendar",
    label: "Calendar",
    category: "Forms",
    description: "Date selection.",
  },
  {
    name: "card",
    label: "Card",
    category: "Layout",
    description: "A composable content surface.",
  },
  {
    name: "carousel",
    label: "Carousel",
    category: "Content",
    description: "Swipeable content.",
  },
  {
    name: "chart",
    label: "Chart",
    category: "Content",
    description: "Charts and tooltips.",
  },
  {
    name: "checkbox",
    label: "Checkbox",
    category: "Forms",
    description: "Single or multiple selections.",
  },
  {
    name: "collapsible",
    label: "Collapsible",
    category: "Content",
    description: "Content on demand.",
  },
  {
    name: "combobox",
    label: "Combobox",
    category: "Forms",
    description: "Searchable selection.",
  },
  {
    name: "command",
    label: "Command",
    category: "Navigation",
    description: "A keyboard-first command palette.",
  },
  {
    name: "context-menu",
    label: "Context Menu",
    category: "Overlay",
    description: "Right-click actions.",
  },
  {
    name: "date-input",
    label: "Date Input",
    category: "Forms",
    description: "A compact native date field.",
  },
  {
    name: "date-picker",
    label: "Date Picker",
    category: "Forms",
    description: "A calendar picker in a popover.",
  },
  {
    name: "dialog",
    label: "Dialog",
    category: "Overlay",
    description: "A focused modal.",
  },
  {
    name: "direction",
    label: "Direction",
    category: "Layout",
    description: "Left-to-right and right-to-left layouts.",
  },
  {
    name: "drawer",
    label: "Drawer",
    category: "Overlay",
    description: "A sliding panel.",
  },
  {
    name: "dropdown-menu",
    label: "Dropdown Menu",
    category: "Overlay",
    description: "Actions behind a trigger.",
  },
  {
    name: "empty",
    label: "Empty",
    category: "Feedback",
    description: "An empty view with a next step.",
  },
  {
    name: "field",
    label: "Field",
    category: "Forms",
    description: "Labels, hints and form controls.",
  },
  {
    name: "hover-card",
    label: "Hover Card",
    category: "Overlay",
    description: "A preview on hover or focus.",
  },
  {
    name: "input",
    label: "Input",
    category: "Forms",
    description: "A text field.",
  },
  {
    name: "input-group",
    label: "Input Group",
    category: "Forms",
    description: "Inputs with prefixes and actions.",
  },
  {
    name: "input-otp",
    label: "Input OTP",
    category: "Forms",
    description: "One-time code entry.",
  },
  {
    name: "item",
    label: "Item",
    category: "Content",
    description: "Rows for lists and results.",
  },
  {
    name: "kbd",
    label: "Kbd",
    category: "Content",
    description: "Keyboard shortcuts.",
  },
  {
    name: "label",
    label: "Label",
    category: "Forms",
    description: "A label for a form control.",
  },
  {
    name: "list",
    label: "List",
    category: "Content",
    description: "Structured rows for metadata and compact data.",
  },
  {
    name: "marker",
    label: "Marker",
    category: "Content",
    description: "Inline highlights.",
  },
  {
    name: "menubar",
    label: "Menubar",
    category: "Navigation",
    description: "Application menus.",
  },
  {
    name: "message",
    label: "Message",
    category: "Content",
    description: "Messages with content and actions.",
  },
  {
    name: "message-scroller",
    label: "Message Scroller",
    category: "Content",
    description: "Scrollable conversations.",
  },
  {
    name: "native-select",
    label: "Native Select",
    category: "Forms",
    description: "A styled native select.",
  },
  {
    name: "navigation-menu",
    label: "Navigation Menu",
    category: "Navigation",
    description: "Navigation with nested panels.",
  },
  {
    name: "pagination",
    label: "Pagination",
    category: "Navigation",
    description: "Move through paged results.",
  },
  {
    name: "password-input",
    label: "Password Input",
    category: "Forms",
    description: "A password field with visibility control.",
  },
  {
    name: "popover",
    label: "Popover",
    category: "Overlay",
    description: "Content anchored to a trigger.",
  },
  {
    name: "progress",
    label: "Progress",
    category: "Feedback",
    description: "Task progress.",
  },
  {
    name: "questionnaire",
    label: "Questionnaire",
    category: "Forms",
    description: "Step-by-step questions.",
  },
  {
    name: "radio-group",
    label: "Radio Group",
    category: "Forms",
    description: "Choose one option.",
  },
  {
    name: "resizable",
    label: "Resizable",
    category: "Layout",
    description: "Panels you can resize.",
  },
  {
    name: "scroll-area",
    label: "Scroll Area",
    category: "Layout",
    description: "Contained scrolling.",
  },
  {
    name: "select",
    label: "Select",
    category: "Forms",
    description: "Choose from a list.",
  },
  {
    name: "separator",
    label: "Separator",
    category: "Layout",
    description: "Separate related content.",
  },
  {
    name: "sheet",
    label: "Sheet",
    category: "Overlay",
    description: "A side panel.",
  },
  {
    name: "sidebar",
    label: "Sidebar",
    category: "Navigation",
    description: "Persistent app navigation.",
  },
  {
    name: "skeleton",
    label: "Skeleton",
    category: "Feedback",
    description: "A loading placeholder.",
  },
  {
    name: "slider",
    label: "Slider",
    category: "Forms",
    description: "Pick a value within a range.",
  },
  {
    name: "spinner",
    label: "Spinner",
    category: "Feedback",
    description: "An activity indicator.",
  },
  {
    name: "switch",
    label: "Switch",
    category: "Forms",
    description: "Toggle a setting.",
  },
  {
    name: "table",
    label: "Table",
    category: "Content",
    description: "Tabular data.",
  },
  {
    name: "tabs",
    label: "Tabs",
    category: "Navigation",
    description: "Switch between related views.",
  },
  {
    name: "textarea",
    label: "Textarea",
    category: "Forms",
    description: "Multi-line text input.",
  },
  {
    name: "toast",
    label: "Toast",
    category: "Feedback",
    description: "Brief action feedback.",
  },
  {
    name: "toggle",
    label: "Toggle",
    category: "Forms",
    description: "A two-state button.",
  },
  {
    name: "toggle-group",
    label: "Toggle Group",
    category: "Forms",
    description: "A group of toggle buttons.",
  },
  {
    name: "tooltip",
    label: "Tooltip",
    category: "Overlay",
    description: "A hint on hover or focus.",
  },
]

export const catalogCategories: ComponentCategory[] = [
  "Forms",
  "Layout",
  "Navigation",
  "Overlay",
  "Feedback",
  "Content",
]
